name: clean_sync
version: 0.5.17
author: Clean Team <clean@vacuumlabs.com>
description: Library for automatic client server synchronization of data.
homepage: http://cleandart.github.io/clean_sync/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://cleandart.github.io/clean_sync/
dependencies:
  clean_ajax: any
  clean_data: any
  logging: '>=0.9.0 <0.10.0'
  mock: any
  mongo_dart: '>=0.1.36 <0.2.00'
  useful: '>=1.0.5 <2.0.0'
  persistent: any
dev_dependencies:
  clean_backend: any
  hop: any
  unittest: '>=0.9.3'

dependency_overrides:
  persistent:
    git:
      url: https://github.com/vacuumlabs/persistent.git
      ref: master
