name: clean_sync
version: 0.8.5
author: Clean Team <clean@vacuumlabs.com>
description: Library for automatic client server synchronization of data.
homepage: http://cleandart.github.io/clean_sync/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://cleandart.github.io/clean_sync/
dependencies:
  clean_ajax: '>=0.4.21'
  clean_data: '>=0.4.9 <0.5.0'
  clean_logging: '>=0.4.2 <0.5.0'
  mock: any
  mongo_dart: '>=0.1.36 <0.2.00'
  useful: '>=1.0.17 <2.0.0'
  clean_lock: '>=0.0.9 <0.1.0'
dev_dependencies:
  clean_backend: '>=0.2.0'
  hop: any
  unittest: '>=0.9.3'
