name: clean_sync
version: 0.3.17
author: Clean Team <clean@vacuumlabs.com>
description: Library for automatic client server synchronization of data.
homepage: http://cleandart.github.io/clean_sync/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://cleandart.github.io/clean_sync/
dependencies:
  clean_ajax:
    path: /home/brandys11/VacuumLabs/clean_ajax
  clean_data:
    path: /home/brandys11/VacuumLabs/clean_data
  logging: '>=0.9.0 <0.10.0'
  mongo_dart: '>=0.1.36 <0.2.0'
  useful: '>=1.0.5'
dev_dependencies:
  clean_backend:
    path: /home/brandys11/VacuumLabs/clean_backend
  hop: any
  unittest: '>=0.9.3'
