name: clean_sync
author: Clean Team <clean@vacuumlabs.com>
version: 0.2.14
homepage: http://cleandart.github.io/clean_sync/
description: Library for automatic client server synchronization of data.
documentation: http://cleandart.github.io/clean_sync/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  clean_ajax:
    path: ../clean_ajax
  clean_data:
    path: ../clean_data
  logging: '>=0.9.0 <0.10.0'
  mongo_dart: '>=0.1.36 <0.2.0'
  useful: any
dev_dependencies:
  clean_backend:
    path: ../clean_backend
  hop: any
  unittest: '>=0.9.3'
