name: clean_sync
version: 0.2.4
author: Clean Team <clean@vacuumlabs.com>
description: Library for automatic client server synchronization of data.
homepage: http://cleandart.github.io/clean_sync/
documentation: http://cleandart.github.io/clean_sync/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  clean_ajax: '>=0.4.0 <0.5.0'
  clean_data: '>=0.3.4 <0.4.0'
  logging: '>=0.9.0 <0.10.0'
  mongo_dart: '>=0.1.36 <0.2.0'
dev_dependencies:
  clean_backend: '>=0.1.0 <0.2.0'
  hop: any
  unittest: any
